- postform-host/Cargo.lock
- postform-host/Cargo.toml
- postform-host/src/lib.rs
- postform-host/src/main.rs
- postform-host/src/postform.rs
Still lots of improvements needed.
> Some progress in host cleanup

- app/build.mk
- app/gcc.ld
- libpostform/postform.ld
We should have a separate linker script for postform and include it in
all user projects.
> Separate linker script for libpostform

- postform_decoder/Cargo.toml
- postform_rtt/Cargo.toml
Preparing for publishing version 0.1.0 of the postform_decoder and
postfor_rtt crates.
> Add cargo metadata

- postform_decoder/src/lib.rs
- postform_persist/src/main.rs
- postform_rtt/src/main.rs
Change-Id: Ie7d555838f9ac6184b369c562916d29f981cddba
> Add postform decoder struct

- postform_decoder/src/lib.rs
* Move some methods back to ElfMetadata.
* Use byteorder methods to read data.
* Remove the need to return the buffer by passing a mutable reference
to it.
Change-Id: I16420338d6696620f0af28b4dbf6ce8babe296d3
> Refactor postform_decoder

- postform_decoder/src/shared_types.rs
Change-Id: I712f35dd9c8d785af0edb7ec54c4f62037aaf0c8
> Fix clippy lints

- postform_decoder/bindings/shared_types.hpp
- postform_decoder/build.rs
Change-Id: Id135b0152de244ce13762119f96a11b7cc143ec1
> Create symlink for bindings

- .github/workflows/main.yml
Change-Id: Id11200ef29d82ea1d533ebc0f5ccbb7ed1000474
> Archive manifest during workflow run

- .clang-format
- app/inc/hal/systick.h
- app/src/hal/systick.cpp
- app/src/host_main.cpp
- app/src/main.cpp
- app/src/postform_config.cpp
- expected_log.txt
- libpostform/build.mk
- libpostform/inc/postform/args.h
- libpostform/inc/postform/config.h
- libpostform/inc/postform/file_logger.h
- libpostform/inc/postform/format_validator.h
- libpostform/inc/postform/logger.h
- libpostform/inc/postform/macros.h
- libpostform/inc/postform/rtt/cobs_writer.h
- libpostform/inc/postform/rtt/raw_writer.h
- libpostform/inc/postform/rtt/rtt.h
- libpostform/inc/postform/rtt/rtt_manager.h
- libpostform/inc/postform/rtt_logger.h
- libpostform/inc/postform/utils.h
- libpostform/src/file_logger.cpp
- libpostform/src/format_validator.cpp
- libpostform/src/macros.cpp
- libpostform/src/platform.cpp
- libpostform/src/rtt/cobs_writer.cpp
- libpostform/src/rtt/raw_writer.cpp
- libpostform/src/rtt/rtt_manager.cpp
- libpostform/test/logger_test.cpp
- libpostform/test/mock_logger.h
Currently these just test the LEB128 functionality.
Change-Id: Ia47fcc1b9f0e7b8540871534fd319311edb0910e
> Add tests for libpostform

- postform_decoder/Cargo.toml
- postform_persist/Cargo.toml
- postform_rtt/Cargo.toml
Change-Id: Ib2471d4e332199363875d58e9cf2b80406a8b1a7
> Bump version number to 0.3.0

- postform_rtt/src/main.rs
Change-Id: Id66e1a3c9364a0b807e6c2d9c26f7ae84c446e7a
> Fix is app running check

- .github/workflows/main.yml
- CMakeLists.txt
Change-Id: I0481adba1821bc9a782a63b951e9c3e254a91382
> Add cmake build to CI

- libpostform/inc/postform/logger.h
We still need to keep the operator _intern because there is no easy way to translate it into a macro.
Added a pragma message to notify the user of the problem and let them know user string interning is not currently possible on GCC.
Relates to #79.
Change-Id: Ia1c51d59f7df41cf9e1e98d3ed4834e53128da5a
> Partially fix string interning on GCC

- CMakeLists.txt
- app/CMakeLists.txt
- cmake/cortex-m_hal.cmake
- cmake/cortex-m_startup.cmake
- cmake/libopencm3.cmake
Change-Id: I6e79d34f8b0acbf0cc63e4036b0086f8f609f519
> Enable cross compilation with CMake

- cmake/libopencm3.cmake
- cmake/toolchains/armv6m.cmake
This will compile the static library, but needs an implementation of
atomics on the armv6m platform.
Change-Id: I8ab141049b46ca6d2567e46863c108be23ad29ce
> Add armv6m.cmake toolchain file

- .github/workflows/main.yml
Change-Id: Ia1fea7d94bae8f1940db77dd71a6a0a2bb767092
> Add CI for multiarch CMake

- libpostform/CMakeLists.txt
Change-Id: Ibada0a0dbb76bde436891f4a88c8c1d62e6e79bc
> Fix version generation in CMake

- postform_rtt/src/main.rs
Change-Id: I84bca7a9481a54f823958147533418a85e697ddd
> Add options to select probe

- libpostform/test/mock_logger.h
- libpostform/test/serial_transport_mock.h
- libpostform/test/timestamp_mock.h
Change-Id: I0a50395dfe6c2d7bf0cb4aac0637c8accdf095b8
> Add missing header guards

- libpostform/inc/postform/serial_logger.h
- libpostform/test/serial_logger_test.cpp
- libpostform/test/serial_transport_mock.h
Change-Id: I5d364ffecddd62724feccab542da4aa1430d5269
> Add reverse COBS for SerialLogger

- app/CMakeLists.txt
- app/inc/hal/flash.h
- app/inc/hal/gpio.h
- app/inc/hal/rcc.h
- app/inc/hal/uart.h
- app/memory.ld
- app/src/main.cpp
- app/src/postform_config.cpp
Change-Id: I241cf819e7d038bf8c432e9a788fe1253420a9da
> Add support for UART in example App

- postform_decoder/src/lib.rs
- postform_rtt/src/lib.rs
Change-Id: I00d351ee79ea95b9fe66bd500959911a436bf654
> Fix clippy warnings

- .github/workflows/main.yml
Change-Id: I4a5cce70b0cfdfb925c21235de86c303047f5882
> Check cargo build in Windows and macOS too

- .github/workflows/main.yml
Change-Id: I3996899299249eb529eb87268e0add911ae1dbec
> Run unit tests for libpostform

- Cargo.lock
- postform_rtt/Cargo.toml
Change-Id: Ie53e7efdaf67b5c00680c2631a487e680d4c44d5
> Update probe-rs to 0.11.0

- postform_rtt/src/lib.rs
When setting a breakpoint for an ARM processor bit 0 is often used to
indicate whether the code we are jumping to is ARM or thumb. Even though
Cortex-M CPUs only support thumb-2 so far, all jump addresses have bit
0 set for this reason.
When setting a breakpoint probe-rs doesn't seem to like this in its
latest release, so let's fix it.
> Reset bit 0 in BP address
